name: 'Setup Ghidra Update Action'
author: 'antoniovazquezblanco'
description: 'Update yout setup-ghidra enabled pipelines'

inputs:
  owner:
    description: 'Owner of the repository to fetch Ghidra version from.'
    default: 'NationalSecurityAgency'
  repo:
    description: 'Repository to fetch Ghidra version from.'
    default: 'ghidra'
  auth_token:
    description: 'GitHub token for authentication.'

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'code'
  color: 'yellow'
